(async()=>{
    const database = {
        account: {
            id: "",
            username: "",
            password: "",
        },
        hero: {
            id: "",
            account_id: "",
            job_id: "",
            name: "",
            hp: "",
            max_hp: "",
            mp: "",
            max_hp: "",
            atk: "",
            def: "",
            matk: "",
            mdef: "",
            str: "",
            agi: "",
            vit: "",
            int: "",
            dex: "",
            luk: "",
            hit: "",
            flee: "",
            crit_rate: "",
            aspd: "",
            exp: "",
            zeny: "",
        },
        job: {},
        skill: {},
        item: {},
        equip: {},
        npc: {},
        enemy: {},
        account: {},
        account: {},
        account: {},
        account: {},
        account: {},
        account: {},
        account: {},
        account: {},
        account: {},
        account: {},
        account: {},
    }
})();